[package]
name = "elornd-bridge"
version = "1.0.0"
authors = [ "David Tanaka <developer@tlchain.network>",]
edition = "2022"
publish = false

[lib]
path = "src/main.rs"

[dependencies.elrond-wasm]
version = "0.31.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.31.1"
